### PR TITLE
Hgc eolt 11 0 x multigain

### PR DESCRIPTION
**Pull request by pfs**
@deguio this PR contains the features for multigain simulation of the ROC
I could not fully erradicate the usage of thickness in the HGCFEElectronics, because apparently it is still used for the evaluation of the timeJitter. However if one looks to the hgcDigitizer_cfi.py the parameterization depending on the thickness is mute as all the parameters are the same. Maybe we can leave this for now as is, and attack it once we review the ToT part alltogether, as it doesn't affect in anything the occupancy estimates?

### CODE REVIEW

**Comment by pfs** [comment]
ups looking to the list of commits in this PR looks like i need to rebase... it includes trigger-related commits which are not needed for this. I'll leave the PR open for now as reference

**Comment by deguio** [comment]
hey @pfs 
I have rebased the main branch `hgc_eolt_11_0_X` on top of pre4 and this one on top of it so things look clean now.
just to make sure I understand correctly. are you suggesting:
- to go ahead and make a PR out of branch `hgc_eolt_11_0_X` and keep working on this one (`hgc_eolt_11_0_X_multigain`) aiming at a later PR?

or 

- to make a PR out of `hgc_eolt_11_0_X_multigain` and complete the eradication in a later stage?

I don't have a strong opinion and either option is fine for me.

**Comment by pfs** [comment]
hey,

thanks! i would propose to go ahead and make a PR out of 
hgc_eolt_11_0_X_multigain, and do the final erradicatin at a later 
stage. I think we need to bring to the attention of the DPG that we need 
to move to a realistic range in the ADC instead of the 100fC version 
that is there now, and when we do that we complete the erradication of 
Si parameters in the FEElectronics class

Cheers,

Pedro

**Comment by deguio** [comment]
sounds good to me. merging this one then.

**Pull request merged**
