### PR TITLE
Add customisation function for towers

### PR DESCRIPTION
**Pull request by jbsauvan**
* Fix tower parameter naming
* Add customisation functions for towers: ideal eta-phi grid and mapping from HGCROCs

### CODE REVIEW

**Comment by jbsauvan** [comment]
@cerminar 
While creating custom functions for towers I have an exception with the HGCROC mapping. 
```
Configuration HGCalTriggerTowerGeometryHelper warning inconsistent mapping TC : 1741541160 to TT iEta: 0 iPhi: 72 when max #bins eta: 18 phi: 72
```
It is probably just a problem with the parameter values I used:
```cpp
def custom_towers_map(process, 
        towermapping='L1Trigger/L1THGCal/data/tower_mapping_hgcroc_eta-phi_v0.txt',
        minEta=1.41,
        maxEta=3.1,
        minPhi=-math.pi,
        maxPhi=math.pi,
        nBinsEta=18,
        nBinsPhi=72
        ):
    parameters_towers_2d = process.hgcalTowerMapProducer.ProcessorParameters.towermap_parameters
    parameters_towers_2d.L1TTriggerTowerConfig.readMappingFile = cms.bool(True)
    parameters_towers_2d.L1TTriggerTowerConfig.L1TTriggerTowerMapping = cms.FileInPath(towermapping)
    parameters_towers_2d.L1TTriggerTowerConfig.minEta = cms.double(minEta)
    parameters_towers_2d.L1TTriggerTowerConfig.maxEta = cms.double(maxEta)
    parameters_towers_2d.L1TTriggerTowerConfig.minPhi = cms.double(minPhi)
    parameters_towers_2d.L1TTriggerTowerConfig.maxPhi = cms.double(maxPhi)
    parameters_towers_2d.L1TTriggerTowerConfig.nBinsEta = cms.int32(nBinsEta)
    parameters_towers_2d.L1TTriggerTowerConfig.nBinsPhi = cms.int32(nBinsPhi)
    return process
```
Does it look ok to you?

**Comment by cerminar** [comment]
Hello @jbsauvan ,
as I mentioned quickly during the last meeting the current mapping has a small problem for 4 HGCROCs in the peripheral region of the detector. (basically ~ no impact on performance)
I recently produced a new mapping, with the same bins used for the TC maps (the current ones are slightly different) and also a version with wafer sums.
I will now produce a PR for this fix.

Cheers,
G

**Comment by jbsauvan** [comment]
Ah ok, thanks, I only caught the comment on the wafer sums version, but not on the HGCROC fix.
So I'll merge this and you can update/add tower customisation functions.

**Comment by cerminar** [comment]
Ops, I just made  PR to this branch to make things easy but you were too fast :(
Let me know if you want me to open a new PR

**Comment by jbsauvan** [comment]
It's ok. I'll merge your PR and create an other PR with the same branch. Thanks.

**Pull request merged**
