### PR TITLE
Adding panel information on a per tc basis

### PR DESCRIPTION
**Pull request by naodell**
Trying again without the indentation modifications.

### CODE REVIEW

**Comment by jbsauvan** [comment]
Thanks @naodell 
Could the branching and filling of these variables be configurable? Because the panel definition actually depends on the actual trigger geometry used and the panel number and sector used here might not be valid in all the cases.

**Comment by jbsauvan** [comment]
You can make the update on the same branch and use the same PR. No need to create a new PR.

**Comment by naodell** [comment]
> You can make the update on the same branch and use the same PR. No need to create a new PR.

Thought I was doing something wrong with making a new PR.  I'll get the hang of this eventually :)

> Could the branching and filling of these variables be configurable? Because the panel definition actually depends on the actual trigger geometry used and the panel number and sector used here might not be valid in all the cases.

This is doable.  What do you envision the configuration as entailing?  Should it simply be that the storage of the variables can be turned on or off?  I'm guessing you would want it to default to being off.

**Comment by jbsauvan** [comment]
You could add a switch where the branches are created and where they are filled. Since the default geometry is compatible, It can be switched on by default.

**Comment by jbsauvan** [comment]
Hi @naodell, any news on this?

**Comment by jbsauvan** [comment]
Closing this PR. This ntuple update has been made available in #329

**Pull request closed without merging**
