### PR TITLE
SimClustering cmssw90

### PR DESCRIPTION
**Pull request by amarini**
Porting #68

### CODE REVIEW

**Comment by amarini** [comment]
SingleGamma Pt 50 (as in testHGCalL1T_cfg.py)
schermata 2017-01-26 alle 10 37 28

**Comment by amarini** [comment]
Added the weighted average with the simhits energy. As expected does barely nothing.
SingleGammaPt35. Energy seems uncalibrated in 90x.
schermata 2017-02-02 alle 09 40 22

**Comment by jbsauvan** [comment]
Hi @amarini 
The energy **is** calibrated. It's probably not perfect but trigger cells should have more or less the correct energy. For instance here you have trigger cell pT sums around a photon of pT=25GeV (the hexagons are not HGCal cells, just histogram bins, the white cross in the middle is the gen photon eta/phi):
image

Here you have the corresponding "sim clusters" (each point is a cluster, color = pT):
image
In that case the two pictures more or less agree. But there are cases where no clusters are created around the photon, or where the cluster map doesn't match with trigger cells like here:
image
image

**Comment by amarini** [comment]
@jbsauvan, 
I'm investigating the problem, I'm trying to feed the sim energy and the n.mips. I hope to have something for beginning next week.
Just for confirmation, is the testHGCalL1T_cfg.py  up to date, right?

~~~python
process.hgcalTriggerPrimitiveDigiProducer.BEConfiguration.algorithms[0].calib_parameters.cellLSB = cms.double(
        process.hgcalTriggerPrimitiveDigiProducer.FECodec.linLSB.value() * 
        2 ** process.hgcalTriggerPrimitiveDigiProducer.FECodec.triggerCellTruncationBits.value()
)
~~~

what I found interesting was that more or less before 
changing the release was roughly peaking somewhere [link](https://cloud.githubusercontent.com/assets/4516989/21312654/b6f901d0-c5ed-11e6-8f35-d606f0059cd8.png), 
while now apparently not.

**Comment by jbsauvan** [comment]
Hi @amarini 
`testHGCalL1T_cfg.py` should be up to date. For what concerns the calibration part it just takes parameters from the offline local reco configs, and the trigger energy coding. You can also use `testHGCalL1T_RelVal_cfg.py`, which takes as input GEN-SIM-DIGI-RAW samples if you want to process events quickly. For instance you can look at these relval samples: [twiki link](https://twiki.cern.ch/twiki/bin/view/CMS/PdmVUpgradeValidation#CMSSW_9_0_0_pre2_CMSSW_8_2_0_pat)
From my quick investigation I have the impression that:
- There are many clusters produced, so the actual photon clusters are maybe hidden 
- Sometimes it seems that one photon actually produces several low energy clusters
- Sometimes no clusters are produced around a given photon

In order to understand better what's going on, we should probably look event by event, photon by photon, what exactly the clusters look like.

**Comment by amarini** [comment]
Finally Working:

SingleGammaPt35:
schermata 2017-02-09 alle 10 52 04

Matching to truth DR<0.1 (top left)
Summing up all collinear clusters (DRtruth<0.1) (bottom right)
schermata 2017-02-09 alle 10 52 25

ClusterShapes:
schermata 2017-02-09 alle 10 52 19

Single GammaPt50 (match to truth):
schermata 2017-02-09 alle 11 00 28

**Comment by jbsauvan** [comment]
Great :-) Can you clean the code and tell me when it can be merged.

**Comment by amarini** [comment]
I cleaned the code, I removed the cout, I put LogWarning and exceptions where relevant. 
I move the input tag in the configuration.
From my side it can be merged. 
I'll start to look at linearity and resolution.

**Comment by jbsauvan** [comment]
Thanks, I'll take a quick look

**Comment by lgray** [comment]
Hooray! I'll buy you a beer next time I am at CERN!

**Pull request merged**
