### PR TITLE
Neighbours finder

### PR DESCRIPTION
**Pull request by amarini**
#4
- Portable implementation of a neighbours finder: may be slow, but should work with any geometry and topology. 
- Not sure if it is better in the library, and eventually call it from the geometry construction 
    geom::initiliaze(..) { ... }
  or have it as a sperate plugin.
- Not sure if you like all constructions. (const_cast, friend) 
- The next thing to add before merging (**TODO**) is the directional navigation n-s-w-e-u-d (here partially suggested)
- @lgray, can you remind me how to run run_matrix, and I will test it.

### CODE REVIEW

**Comment by lgray** [comment]
@amarini any progress here?

**Comment by amarini** [comment]
I'll work on it tomorrow.

**Comment by amarini** [comment]
@lgray, I removed the access to const stuff, preparing first (non-const), modify, and finalize (make const).
I also added directional navigation.

**Comment by amarini** [comment]
I still need to test it.

**Comment by lgray** [comment]
Great, thanks!

**Comment by amarini** [comment]
@lgray, @jbsauvan 
I found an orphan (cell 2356):
$cat cellsToTriggerCellsMap.txt  | grep -A 2 '^29\ +1\ +235'

( layer, subsec, cell)  -> (mod, trigger cel) . (zside and sector are looped) 
29  1 2350 19 40 
29  1 2351 19 40 
29  1 2352 19 41 
29  1 2353 19 41 
29  1 2354 19 42 
29  1 2355 19 42 
30 -1 0    1  4  

that it is defined in the underlying HGCal geometry:
1743595828 =  cell 2356 | sec = 18 | sub = 1 | layer = 29 | zside = 1 

HGCal Cell ID=1743595828 referenced in trigger cell (id=1676298666)  components:1743595827: N 1743595856|S 1743595798| **E 1743595828** |W 1743595826|U 1744120115|D 1743071539|
1743595826: N 1743595855|S 1743595797|E 1743595827|W 1743595825|U 1744120114|D 1743071538|
1743595798: N 1743595827|S 1743595769|E 1743595799|W 1743595797|U 1744120086|D 1743071510|
1743595797: N 1743595826|S 1743595768|E 1743595798|W 1743595796|U 1744120085|D 1743071509|
, but not present in the map

at the moment I throw an exception.

**Comment by jbsauvan** [comment]
@amarini thanks for spotting. I will check with @puljak in which module/trigger cell we should put this orphan cell. Is it happening only in layer 29?

**Comment by amarini** [comment]
If my counts are correct you forget 1652 cells ( that get multiplied by 2 and by the sector 18 to map into the hgcal cells).
~amarini/public/hgcal_detid.txt

**Comment by jbsauvan** [comment]
@amarini Are these physical cells? Did you check where they are located? I saw before cells which were not included in trigger cells, but these were unphysical. You see for instance in the picture below the red lines, that correspond to cells not attached to trigger cells (ROOT did not draw the full squares for some reason but they are all below the long red line on the right side). These cells extend far beyond the petals. So can you check where are your orphan cells?
triggercellmap

**Comment by amarini** [comment]
@jbsauvan do you know a smart method to check if the cell is a good cell ?

**Comment by jbsauvan** [comment]
@amarini To define the trigger cells we looked at the cell ids from the SimHits, so these were all cells with some energy. 
Otherwise in the HGCalTopology class there is the method valid(DetId&), but it should already been called in the navigation method, and the red cells above are anyway supposed to be "valid".
It is still possible that some real cells have been missed when defining the trigger cells, but the red cells above are weird because the row is extending beyond the limit of the petal. So for the moment I don't really know what to say about them. 
Maybe you could first cross-check that the orphan cells that you see are at the same place as mine?

**Comment by amarini** [comment]
I ignore the cells that are not in the trigger geometry. Fixed also a couple of bugs. Now should run.

**Comment by amarini** [comment]
The z neighbour are likely to be broken for our purposes: if we miss layers, tr cell neighbour are not hgcal neighbour anymore .

**Comment by jbsauvan** [comment]
@amarini do you still want to merge this PR or we can close it? Now we are moving the developments to the 81X releases with the hex geometry.

**Pull request closed without merging**
