### PR TITLE
 Creating coarse trigger cells - (10_6_0_pre4) v2

### PR DESCRIPTION
**Pull request by snwebb**
A continuation of #319 and #340

### CODE REVIEW

**Comment by jbsauvan** [comment]
It seems there are issues with STC in V9Impl2 in the previous implementation (see #359)
Do you know if the version implemented here fixes this?

**Comment by snwebb** [comment]
It might fix some things, but there is a large difference between impl1 and impl2, which I don't understand.

**Comment by jbsauvan** [comment]
To merge the PR quickly, it would then maybe be better to implement the scintillator support for the V8 detids. Is it something that can be implemented quickly?

**Comment by snwebb** [comment]
I would say it's not too easy to do. I would probably say that it's probably not a big effect not having the Scintillator available for STCs. If you merge this now I can work on a bug fix for the v9, or we can try to wait to see if it is easily solved (I might know soon).

**Comment by snwebb** [comment]
Actually I think the issue is that the STC id for impl2 is not necessarily a real trigger cell id (due to the rotation and creation of a pseudo-id, with u-prime).

**Comment by jbsauvan** [comment]
> I would say it's not too easy to do. I would probably say that it's probably not a big effect not having the Scintillator available for STCs.

For cluster shapes it might probably have an impact. So I would really prefer to have this working one way or an other, to have realistic results to show at the workshop.

**Comment by jbsauvan** [comment]
Comparison for 4,16,16 in V9Impl1 (no coarsening in scintillator) looks fine: [Validation plots](https://jsauvan.web.cern.ch/jsauvan/private/hgcal/validation/pr360_stc_4_16/)

**Comment by snwebb** [comment]
equal-share
EqualShare v9 impl1 and impl2

one-bit-fraction
One bit fraction v9 impl1 and impl2

super-trigger-cell

SuperTriggerCell v9 impl1 and impl2

Differences due to missing scintillator support for impl1

**Comment by jbsauvan** [comment]
Thanks, do you have also the plots removing the scintillator?

**Comment by snwebb** [comment]
super-trigger-cell-4-16-16-1
Super Trigger Cell, with `stcSize = 4,16,16,1' for both impl1 and impl2 (exactly the same)

**Pull request merged**
