### PR TITLE
Add custom function and test config for standalone clustering

### PR DESCRIPTION
**Pull request by jbsauvan**
Adding:
- a customization function to use the standalone clustering implementation.
- a ntuple customization to use the cluster collection produced by the standalone clustering
- a test config to run the standalone clustering

### CODE REVIEW

**Comment by jbsauvan** [comment]
Hi @EmyrClement 
Here is PR adding customization functions and test configs to use the standalone clustering. Could you cross-check that it runs as expected and that I didn't miss additional parameter changes?
Thanks!

**Comment by EmyrClement** [comment]
Hi @jbsauvan this looks ok to me and runs as expected.  Should we also add the customisations to run the standalone stage 2 tower sums given the new structure exists for that?

**Comment by jbsauvan** [comment]
Thanks @EmyrClement for the checks!
Right, I can add the tower customization as well.

**Comment by jbsauvan** [comment]
Hi @EmyrClement 
I have added a custom for the towers as well.
When runnning the standalone tower processor, I noticed that the eta and phi of the towers are always 0, and that the pT distribution is much softer.
Could you have a look?
Thanks!

**Comment by EmyrClement** [comment]
Hi @jbsauvan regarding the tower pT, this is likely because I did not include the unclustered TCs when producing the towers in the standalone wrapper - the structure of the towers code is closer to the firmware structure, but the inputs and output towers won't therefore make much sense.  I ran the existing simulation with ```includeTrigCells``` set to false for the tower producer, which gives a pT distribution closer to what I get with the standalone code, but not identical.  Is it worth fixing this in the standalone code?

For the eta and phi of the towers, I realised I had not carried them through the standalone code - it's straightforward to fix this.

**Comment by jbsauvan** [comment]
Hi @EmyrClement 
Ok, thanks. That's fine not to include the TCs; anyway I switch to not including the TCs also in the default towers (#477).
Concerning eta/phi, could you open a separate PR with the fix?

**Comment by EmyrClement** [comment]
I opened #479 to address the eta/phi fix.

**Comment by jbsauvan** [comment]
Thanks @EmyrClement 
I just merged #479

**Pull request merged**
