### PR TITLE
Adapt FE and clustering thresholds to new calibration used on samples with V9 geometry

### PR DESCRIPTION
**Pull request by cerminar**
The PR addresses the problem of adapting the cuts in MiPPT to the new calibration schema used for samples produced with V9 geometry.
The switch is handled via the era mechanism.

The following thresholds are changed:
- TC selection threshold in FE selection -> from 2 to 1.5 MIPT
- HistoMax seed threshold -> from 10 to 7.5 MIPPT

The validation plots show the distribution of the TC charge after selection for 100 (x2) photons with eta 2.

V9 geometry and thresholds:
tccharge_V9

V8 geometry and thresholds:
tccharge_V8

Supersedes #312 

**NOTE**:  the default parameters in the functions used by the `HGCalTriggerChains`  utilities [create_threshold](https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_10_6_0_pre2/L1Trigger/L1THGCalUtilities/python/concentrator.py#L16) and [create_histoMax_variableDr](https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_10_6_0_pre2/L1Trigger/L1THGCalUtilities/python/clustering3d.py#L54) will silently roll back to the values of the V89 geometry (for the FE) and to yet a different value for the 3D clustering seed. Any chance we could address this? Maube just removing the defaults?

### CODE REVIEW

**Comment by cerminar** [comment]
> NOTE: the default parameters in the functions used by the HGCalTriggerChains utilities create_threshold and create_histoMax_variableDr will silently roll back to the values of the V89 geometry (for the FE) and to yet a different value for the 3D clustering seed. Any chance we could address this? Maube just removing the defaults?

Another option (that I actually like better) is to default all parameters to `None`, clone the original psets and actually change explicitly only the parameters which are not `None`.
This would also reduce code duplication quite a lot and allow all the era modifications to remain be effective.

**Comment by jbsauvan** [comment]
But the original PSets might not contain the needed parameters if it was defined for a different algo that requires different parameters. 
A solution could be to define all default parameters in separate PSets like here:
https://github.com/cms-sw/cmssw/blob/master/SimCalorimetry/HGCalSimProducers/python/hgcalDigitizer_cfi.py#L11-L13
Then we pass these PSets as default values of the function parameters. And the era modifiers change these PSets which will be propagated to the function defaults.

**Comment by cerminar** [comment]
You are right. This would also avoid the code duplication with all the "custom*.py" modules: you could use the same psets also there.

**Comment by jbsauvan** [comment]
I'm tracking this in #317

**Pull request closed without merging**
