### PR TITLE
Change default V9 trigger geometry to V9Imp2

### PR DESCRIPTION
**Pull request by jbsauvan**
No change for default TPG chain (threshold + HistoMax)
[Validation plots](https://jsauvan.web.cern.ch/jsauvan/private/hgcal/validation/V9Impl1vs2/)

### CODE REVIEW

**Comment by jbsauvan** [comment]
@snwebb there are quite significant issues with STC in V9Impl2:
[plots](https://jsauvan.web.cern.ch/jsauvan/private/hgcal/validation/pr359_stc/)

**Comment by snwebb** [comment]
Yes, I was just looking at something similar myself and trying to work it out.

**Comment by jbsauvan** [comment]
No change for BestChoice selection: [plots](https://jsauvan.web.cern.ch/jsauvan/private/hgcal/validation/pr359_bc/)

**Comment by jbsauvan** [comment]
V9Impl1 and V9Impl2 have been compared for STC/CTC options in #360 and distributions agree.

**Pull request merged**
